Fix AttributeError: 'TerminalWriter' object has no attribute '_write_source' (#52)
* Fix diagnostics formatting with pytest 5.4

py.io.TerminalWriter is not supported anymore since pytest now expects
its custom subclass instead (_pytest._io.TerminalWriter), but
pytest.reports.BaseReport.longreprtext provides us with a good
alternative whose implementation is very similar to what we had.

* Require pytest >= 3

pytest-tap uses pytest’s BaseReport.longreprtext, which was introduced
in pytest 3.0 according to pytest’s documentation.

* Add myself to AUTHORS